#version: "3.9"  
services:

  store_api:
    build:
      context: ./APIS
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "52000:52000"
    volumes:
      - ./APIS/Store/:/sto/storeAPI/  
    depends_on:
      - db
    networks:
      - dev_network
  db:
    image: postgres:16
    shm_size: 128mb
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 2GB
        reservations:
          cpus: "0.1"
          memory: 1GB
    environment:
      POSTGRES_PASSWORD: 98765
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/store:/var/lib/postgresql/data
    networks:
      - dev_network

  pgadmin:
        image: dpage/pgadmin4
        container_name: distri_pgadmin
        ports:
          - "8888:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: narvaez@nar.com
          PGADMIN_DEFAULT_PASSWORD: 12345
        volumes:
          - ./pgadmin-data:/var/lib/pgadmin
        networks:
          - dev_network
networks:
  dev_network:
    driver: bridge

